export const constants = {
  rectsDivClassName: ".rect-container",
  eyeDetectionOutlineClassName: "rectangle",
  rectTransparentColorClassName: "transparent-rect",
  specDivClassName: "#spec",
  nextSpecBtnPath: "assets/static/next.png",
  prevSpecBtnPath: "assets/static/prev.png",
  cameraShutterImgSrc: "assets/static/camera-shutter.png",
  trySpecsDisabledIcon: "assets/static/disabled-spec-icon.png",
  trySpecsIcon: "assets/static/spec-icon.png",

  animations: {
    cameraShutterOnClassName: "camera-shutter-on",
    cameraShutterOffClassName: "camera-shutter-off",
  },

  specPaths: [
    "assets/specs/black-round2.png",
    "assets/specs/black-rect1.png",
    "assets/specs/black-rect2.png",
    "assets/specs/black-tri1.png",
    "assets/specs/blue-rect1.png",
    "assets/specs/blue-round2.png",
    "assets/specs/blue-tri1.png",
    "assets/specs/green-rect2.png",
    "assets/specs/green-round2.png",
    "assets/specs/orange-rect1.png",
    "assets/specs/orange-tri1.png",
    "assets/specs/perssian-round2.png",
    "assets/specs/pink-rect1.png",
    "assets/specs/pink-tri1.png",
    "assets/specs/purple-rect2.png",
    "assets/specs/red-rect2.png",
  ],
};
